python multiple-choice/run_swag.py \
  --model_name_or_path "output/chinese-roberta-wwm-ext-large/cs" \
  --cache_dir "cache/chinese-roberta-wwm-ext-large" \
  --test_file swag_test.json \
  --max_seq_length 512 \
  --output_dir "output/test_cs" \
  --do_predict \
  --num_train_epochs 3 \
  --lr_scheduler_type linear \
  --seed 42 \
  --fp16 \
  --report_to all \
  --resume_from_checkpoint "output/chinese-roberta-wwm-ext-large/cs"
